lang: r
before_install:
    - sudo apt-get install pandoc texlive texlive-latex-base
script:
    - pandoc --template template.html -o dist/index.html bylaws.md
    - pandoc -t latex -o dist/bylaws.pdf bylaws.md
deploy:
    local-dir: dist/
    provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    on:
        branch: master
